### ISSUE TITLE
nas 构建docker 启动提示错误

### ISSUE THREAD

**Issue by shaoyingrui** [nicejade/wealth-tracker#1]
exec user process caused: exec format error

**Comment by shaoyingrui** [comment]
貌似 Docker版本不支持Arm64

**Comment by nicejade** [comment]
@shaoyingrui  感谢反馈。

您的判断是正确的；支持 ARM 架构设备镜像已发布（`1.3.0`），详见：[wealth-tracker tag](https://hub.docker.com/repository/docker/nicejade/wealth-tracker/tags)。

先前，在本地构建时候，有尝试一次性支持 AMD 和 ARM 架构的镜像，未有成功；此外，因为众所周知的原因，很多环境下不能使用 Docker Hub 镜像，于是就停止了探究；更侧重基于其它方案如 `pm2` 来部署。

截止目前， 尚未寻找到合适方案，ARM 和 AMD 两个版本的镜像，只能单独发布；倘若有需要基于 Docker 部署，可 `clone` 项目至本地，构建本地镜像来使用：

```bash
docker build -t wealth-tracker .
```

后续，代码更新，会尽可能发布至 Docker Hub；对于您的反馈，再次感谢。

**Comment by nicejade** [comment]
@shaoyingrui  在后续更新的版本中，对  arm64、amd64 均做了支持，欢迎再次试用： https://hub.docker.com/r/nicejade/wealth-tracker/tags 。没有支持更多架构，详情可参见：https://github.com/nicejade/wealth-tracker/issues/3 。

对您的反馈，非常感谢；欢迎提出更多宝贵建议或意见。接下来，重心将转移至与 AI 结合，敬请关注 🫰。
