### ISSUE TITLE
试用了下，发现几个问题

### ISSUE THREAD

**Issue by joetin** [nicejade/wealth-tracker#2]
试用了下，发现几个问题
1.没有找到资产删除的地方，一旦新增就无法删除（如果想删除，应该如何处理？）
2.在记录详情中可以修改历史， 但修改过的历史无法反映到一览中。
3.有两个“资产趋势”，其实一个是“各资产趋势”，一个是“总资产趋势”，建议修改描述，使其逻辑更清晰。
4.建议主页最下方增加版本号描述
5.不让人修改类型名称有点反直觉，毕竟一次就取对名字有点难（可能：））

**Comment by nicejade** [comment]
@joetin 非常感谢提出的建议（非常抱歉，国庆假期前后没怎么关注到消息提醒）。

1. 我原想的是资产数字`清 0` （昨晚在更新自己资产时候，发现这样并不友好，它仍会占据趋势图表的一席之地）；—— 会尽快修复这个设计缺陷。
2. 按照设想，修改过的历史，应该要反映到「趋势图表📈中」；——需要查下代码是否存在缺陷；
3. 嗯嗯，很赞成，先前添加“总资产趋势”📈，也存有这个感觉，因为没有想好怎么更好区分就先搁浅了；——我再考虑下；
4. 嗯嗯，很赞的建议，下个版本加上。
5. 赞👍🏻；很好的建议（也是在使用一段时间后发现这个问题）；还没有处理，是没想好怎么兼容之前已经记录的数据（如果采用方案：改变类型为普通字段、增加  `id` 关键字段）；—— 看来：尽早是最佳的时机。

再次对您的宝贵建议，表示感谢 ❤️   —— 如需增加额外需求，这边会优先考虑。

**Comment by nicejade** [comment]
@joetin  晚上好，您之前提及的 5 个问题，均已修复、测试，并发布至 Docker Hub，详情参见：[docker hub wealth-tracker](https://hub.docker.com/r/nicejade/wealth-tracker)，欢迎再次试用；对您的反馈，非常感谢；欢迎提出更多宝贵建议或意见。接下来，重心将转移至与 AI 结合，敬请关注 🫰。
