### ISSUE TITLE
【BUG】资产变化后面的百分比

### ISSUE THREAD

**Issue by a810439322** [nicejade/wealth-tracker#5]
选项变动的时候，资产升降百分比也应该跟着变化，比如我只选基金，这里应该是-33%
![image](https://github.com/user-attachments/assets/e823e9b9-4f3a-4562-a70e-b28f6fa91557)

**Comment by nicejade** [comment]
嗯嗯，这样联动设计，对于用户来讲，更有帮助；会尽快处理下。感谢您提出的宝贵建议👏。

小付同学 ***@***.***> 于2024年11月26日周二 14:04写道：

**Comment by nicejade** [comment]
只是告诉它需求，发起了两轮聊天，Windsurf 就帮助优化了这个问题，再一次感受到 Codeium Windsurf 的强大。
